/**
 * MessagingEngine — rules for chat between two matched users.
 *
 * Pure decision logic. The MessageService persists messages
 * via the MessageRepository.
 *
 * Rules:
 *   - Users can message only after matching
 *   - Users cannot message blocked users
 *   - Messages belong to a match
 *   - Empty messages are rejected
 *   - Messages have a max length
 *   - Deleted / blocked matches cannot continue messaging
 *   - Timestamps are generated by the engine (via the clock)
 */

import { MESSAGE_LIMITS } from '../core/constants.js';

export class MessagingEngine {
  constructor({ clock }) {
    if (!clock) throw new Error('MessagingEngine requires a clock');
    this.clock = clock;
  }

  /**
   * @returns {{ allowed: boolean, code?: string, reason?: string }}
   */
  canSendMessage({ senderId, match, blockedEitherDirection = false }) {
    if (!senderId) {
      return deny('VALIDATION_FAILED', 'senderId is required');
    }
    if (!match) {
      return deny('NOT_MATCHED', 'No match between these users');
    }
    if (match.blocked === true || blockedEitherDirection) {
      return deny('USER_BLOCKED', 'Messaging is disabled for blocked users');
    }
    if (match.deleted === true) {
      return deny('NOT_MATCHED', 'Match has been deleted');
    }
    if (!Array.isArray(match.users) || !match.users.includes(senderId)) {
      return deny('NOT_MATCHED', 'Sender is not a participant in this match');
    }
    return { allowed: true };
  }

  /**
   * Prepare a message payload from raw input.
   * Throws if the message is empty or too long.
   * @returns {{ matchId: string, senderId: string, body: string, createdAt: number }}
   */
  prepare({ matchId, senderId, body }) {
    if (typeof body !== 'string') {
      const e = new Error('Message body must be a string');
      e.code = 'MESSAGE_EMPTY';
      throw e;
    }
    const trimmed = body.trim();
    if (trimmed.length < MESSAGE_LIMITS.MIN_LENGTH) {
      const e = new Error('Message cannot be empty');
      e.code = 'MESSAGE_EMPTY';
      throw e;
    }
    if (trimmed.length > MESSAGE_LIMITS.MAX_LENGTH) {
      const e = new Error(`Message must be at most ${MESSAGE_LIMITS.MAX_LENGTH} characters`);
      e.code = 'MESSAGE_TOO_LONG';
      throw e;
    }
    return {
      matchId,
      senderId,
      body: trimmed,
      createdAt: this.clock.now(),
    };
  }

  /**
   * Sort a conversation chronologically. Stable: same createdAt keeps input order.
   */
  sortConversation(messages = []) {
    return messages
      .map((m, i) => ({ m, i }))
      .sort((a, b) => {
        if (a.m.createdAt !== b.m.createdAt) return a.m.createdAt - b.m.createdAt;
        return a.i - b.i;
      })
      .map((x) => x.m);
  }

  /**
   * Preview text for a chat list row.
   */
  preview(message, maxLength = 60) {
    if (!message?.body) return '';
    const b = message.body.replace(/\s+/g, ' ').trim();
    if (b.length <= maxLength) return b;
    return b.slice(0, maxLength - 1).trimEnd() + '…';
  }
}

function deny(code, reason) {
  return { allowed: false, code, reason };
}
